var hierarchy =
[
    [ "application.types.blob_storage.BlobStorage", "classapplication_1_1types_1_1blob__storage_1_1BlobStorage.html", [
      [ "application.types.blob_storage.BlobPreview", "classapplication_1_1types_1_1blob__storage_1_1BlobPreview.html", null ],
      [ "application.types.blob_storage.BlobThumbnail", "classapplication_1_1types_1_1blob__storage_1_1BlobThumbnail.html", null ]
    ] ],
    [ "Exception", null, [
      [ "application.exceptions.ClientError", "classapplication_1_1exceptions_1_1ClientError.html", [
        [ "application.exceptions.AuthenticationError", "classapplication_1_1exceptions_1_1AuthenticationError.html", null ],
        [ "application.exceptions.BadUserNameError", "classapplication_1_1exceptions_1_1BadUserNameError.html", null ],
        [ "application.exceptions.BlobDoesNotExistError", "classapplication_1_1exceptions_1_1BlobDoesNotExistError.html", null ],
        [ "application.exceptions.BookCannotBeShared", "classapplication_1_1exceptions_1_1BookCannotBeShared.html", null ],
        [ "application.exceptions.BookTagDoesNotExistError", "classapplication_1_1exceptions_1_1BookTagDoesNotExistError.html", null ],
        [ "application.exceptions.BookTagExistsError", "classapplication_1_1exceptions_1_1BookTagExistsError.html", null ],
        [ "application.exceptions.BugReportDoesNotExistError", "classapplication_1_1exceptions_1_1BugReportDoesNotExistError.html", null ],
        [ "application.exceptions.FeedDocumentDoesNotExistError", "classapplication_1_1exceptions_1_1FeedDocumentDoesNotExistError.html", null ],
        [ "application.exceptions.FeedDoesNotExistError", "classapplication_1_1exceptions_1_1FeedDoesNotExistError.html", null ],
        [ "application.exceptions.InsufficientDiskSpace", "classapplication_1_1exceptions_1_1InsufficientDiskSpace.html", null ],
        [ "application.exceptions.InvalidFeedKindError", "classapplication_1_1exceptions_1_1InvalidFeedKindError.html", null ],
        [ "application.exceptions.InvalidSubscriptionToken", "classapplication_1_1exceptions_1_1InvalidSubscriptionToken.html", null ],
        [ "application.exceptions.ItemDoesNotExistError", "classapplication_1_1exceptions_1_1ItemDoesNotExistError.html", null ],
        [ "application.exceptions.ItemExistsError", "classapplication_1_1exceptions_1_1ItemExistsError.html", null ],
        [ "application.exceptions.MissingConfig", "classapplication_1_1exceptions_1_1MissingConfig.html", null ],
        [ "application.exceptions.SubsonicError", "classapplication_1_1exceptions_1_1SubsonicError.html", null ],
        [ "application.exceptions.UserDoesNotExistError", "classapplication_1_1exceptions_1_1UserDoesNotExistError.html", null ],
        [ "application.exceptions.UserExistsError", "classapplication_1_1exceptions_1_1UserExistsError.html", null ],
        [ "application.exceptions.WebPushException", "classapplication_1_1exceptions_1_1WebPushException.html", null ]
      ] ],
      [ "application.integrations.exceptions.ApiFailedError", "classapplication_1_1integrations_1_1exceptions_1_1ApiFailedError.html", null ],
      [ "application.integrations.exceptions.RepoFetchFailed", "classapplication_1_1integrations_1_1exceptions_1_1RepoFetchFailed.html", null ],
      [ "application.integrations.exceptions.UnsupportedFileFormat", "classapplication_1_1integrations_1_1exceptions_1_1UnsupportedFileFormat.html", null ]
    ] ],
    [ "application.integrations.github.Repository", "classapplication_1_1integrations_1_1github_1_1Repository.html", [
      [ "application.integrations.github.CurrentRepository", "classapplication_1_1integrations_1_1github_1_1CurrentRepository.html", null ]
    ] ],
    [ "ValueError", null, [
      [ "application.exceptions.InvalidColor", "classapplication_1_1exceptions_1_1InvalidColor.html", null ],
      [ "application.exceptions.InvalidPhone", "classapplication_1_1exceptions_1_1InvalidPhone.html", null ],
      [ "application.exceptions.InvalidSize", "classapplication_1_1exceptions_1_1InvalidSize.html", null ]
    ] ],
    [ "MutationType", null, [
      [ "application.resolvers.mutation.MutationWrapper", "classapplication_1_1resolvers_1_1mutation_1_1MutationWrapper.html", null ]
    ] ],
    [ "TypedDict", null, [
      [ "application.objects.BlobSearchFilter", "classapplication_1_1objects_1_1BlobSearchFilter.html", null ],
      [ "application.objects.BookSearchFilter", "classapplication_1_1objects_1_1BookSearchFilter.html", null ],
      [ "application.objects.InventorySearchFilter", "classapplication_1_1objects_1_1InventorySearchFilter.html", null ],
      [ "application.objects.Sorting", "classapplication_1_1objects_1_1Sorting.html", null ],
      [ "application.types._theme._Theme", "classapplication_1_1types_1_1__theme_1_1__Theme.html", null ],
      [ "application.types.apifailederror.ApiFailedError", "classapplication_1_1types_1_1apifailederror_1_1ApiFailedError.html", null ],
      [ "application.types.apikey.APIKey", "classapplication_1_1types_1_1apikey_1_1APIKey.html", null ],
      [ "application.types.badnotification.BadNotification", "classapplication_1_1types_1_1badnotification_1_1BadNotification.html", null ],
      [ "application.types.badtagquery.BadTagQuery", "classapplication_1_1types_1_1badtagquery_1_1BadTagQuery.html", null ],
      [ "application.types.badusernameerror.BadUserNameError", "classapplication_1_1types_1_1badusernameerror_1_1BadUserNameError.html", null ],
      [ "application.types.blob.Blob", "classapplication_1_1types_1_1blob_1_1Blob.html", null ],
      [ "application.types.blobcount.BlobCount", "classapplication_1_1types_1_1blobcount_1_1BlobCount.html", null ],
      [ "application.types.blobdoesnotexisterror.BlobDoesNotExistError", "classapplication_1_1types_1_1blobdoesnotexisterror_1_1BlobDoesNotExistError.html", null ],
      [ "application.types.bloblist.BlobList", "classapplication_1_1types_1_1bloblist_1_1BlobList.html", null ],
      [ "application.types.blobsearchfilter.BlobSearchFilter", "classapplication_1_1types_1_1blobsearchfilter_1_1BlobSearchFilter.html", null ],
      [ "application.types.book.Book", "classapplication_1_1types_1_1book_1_1Book.html", null ],
      [ "application.types.bookcannotbeshared.BookCannotBeShared", "classapplication_1_1types_1_1bookcannotbeshared_1_1BookCannotBeShared.html", null ],
      [ "application.types.bookcreatedata.BookCreateData", "classapplication_1_1types_1_1bookcreatedata_1_1BookCreateData.html", null ],
      [ "application.types.bookeditdata.BookEditData", "classapplication_1_1types_1_1bookeditdata_1_1BookEditData.html", null ],
      [ "application.types.bookident.BookIdent", "classapplication_1_1types_1_1bookident_1_1BookIdent.html", null ],
      [ "application.types.booklist.BookList", "classapplication_1_1types_1_1booklist_1_1BookList.html", null ],
      [ "application.types.bookownerhist.BookOwnerHist", "classapplication_1_1types_1_1bookownerhist_1_1BookOwnerHist.html", null ],
      [ "application.types.booksearchfilter.BookSearchFilter", "classapplication_1_1types_1_1booksearchfilter_1_1BookSearchFilter.html", null ],
      [ "application.types.bookshare.BookShare", "classapplication_1_1types_1_1bookshare_1_1BookShare.html", null ],
      [ "application.types.booktag.BookTag", "classapplication_1_1types_1_1booktag_1_1BookTag.html", null ],
      [ "application.types.booktagdoesnotexisterror.BookTagDoesNotExistError", "classapplication_1_1types_1_1booktagdoesnotexisterror_1_1BookTagDoesNotExistError.html", null ],
      [ "application.types.booktagexistserror.BookTagExistsError", "classapplication_1_1types_1_1booktagexistserror_1_1BookTagExistsError.html", null ],
      [ "application.types.bugcomment.BugComment", "classapplication_1_1types_1_1bugcomment_1_1BugComment.html", null ],
      [ "application.types.bugreport.BugReport", "classapplication_1_1types_1_1bugreport_1_1BugReport.html", null ],
      [ "application.types.bugreportcreationfailederror.BugReportCreationFailedError", "classapplication_1_1types_1_1bugreportcreationfailederror_1_1BugReportCreationFailedError.html", null ],
      [ "application.types.bugreportdoesnotexisterror.BugReportDoesNotExistError", "classapplication_1_1types_1_1bugreportdoesnotexisterror_1_1BugReportDoesNotExistError.html", null ],
      [ "application.types.config.Config", "classapplication_1_1types_1_1config_1_1Config.html", null ],
      [ "application.types.configlist.ConfigList", "classapplication_1_1types_1_1configlist_1_1ConfigList.html", null ],
      [ "application.types.diskusage.DiskUsage", "classapplication_1_1types_1_1diskusage_1_1DiskUsage.html", null ],
      [ "application.types.ebook.EBook", "classapplication_1_1types_1_1ebook_1_1EBook.html", null ],
      [ "application.types.feed.Feed", "classapplication_1_1types_1_1feed_1_1Feed.html", null ],
      [ "application.types.feeddocument.FeedDocument", "classapplication_1_1types_1_1feeddocument_1_1FeedDocument.html", null ],
      [ "application.types.feeddocumentdoesnotexisterror.FeedDocumentDoesNotExistError", "classapplication_1_1types_1_1feeddocumentdoesnotexisterror_1_1FeedDocumentDoesNotExistError.html", null ],
      [ "application.types.feeddoesnotexisterror.FeedDoesNotExistError", "classapplication_1_1types_1_1feeddoesnotexisterror_1_1FeedDoesNotExistError.html", null ],
      [ "application.types.insufficientdiskspace.InsufficientDiskSpace", "classapplication_1_1types_1_1insufficientdiskspace_1_1InsufficientDiskSpace.html", null ],
      [ "application.types.insufficientperms.InsufficientPerms", "classapplication_1_1types_1_1insufficientperms_1_1InsufficientPerms.html", null ],
      [ "application.types.invalidfeedkinderror.InvalidFeedKindError", "classapplication_1_1types_1_1invalidfeedkinderror_1_1InvalidFeedKindError.html", null ],
      [ "application.types.invalidfields.InvalidFields", "classapplication_1_1types_1_1invalidfields_1_1InvalidFields.html", null ],
      [ "application.types.invalidsubscriptiontoken.InvalidSubscriptionToken", "classapplication_1_1types_1_1invalidsubscriptiontoken_1_1InvalidSubscriptionToken.html", null ],
      [ "application.types.inventorysearchfilter.InventorySearchFilter", "classapplication_1_1types_1_1inventorysearchfilter_1_1InventorySearchFilter.html", null ],
      [ "application.types.issuelabel.IssueLabel", "classapplication_1_1types_1_1issuelabel_1_1IssueLabel.html", null ],
      [ "application.types.issuelist.IssueList", "classapplication_1_1types_1_1issuelist_1_1IssueList.html", null ],
      [ "application.types.item.Item", "classapplication_1_1types_1_1item_1_1Item.html", null ],
      [ "application.types.itemdoesnotexisterror.ItemDoesNotExistError", "classapplication_1_1types_1_1itemdoesnotexisterror_1_1ItemDoesNotExistError.html", null ],
      [ "application.types.itemexistserror.ItemExistsError", "classapplication_1_1types_1_1itemexistserror_1_1ItemExistsError.html", null ],
      [ "application.types.lastmutation.LastMutation", "classapplication_1_1types_1_1lastmutation_1_1LastMutation.html", null ],
      [ "application.types.logresult.LogResult", "classapplication_1_1types_1_1logresult_1_1LogResult.html", null ],
      [ "application.types.missingconfig.MissingConfig", "classapplication_1_1types_1_1missingconfig_1_1MissingConfig.html", null ],
      [ "application.types.mutation.Mutation", "classapplication_1_1types_1_1mutation_1_1Mutation.html", null ],
      [ "application.types.notification.Notification", "classapplication_1_1types_1_1notification_1_1Notification.html", null ],
      [ "application.types.qrparseresponse.QRParseResponse", "classapplication_1_1types_1_1qrparseresponse_1_1QRParseResponse.html", null ],
      [ "application.types.query.Query", "classapplication_1_1types_1_1query_1_1Query.html", null ],
      [ "application.types.repofetchfailed.RepoFetchFailed", "classapplication_1_1types_1_1repofetchfailed_1_1RepoFetchFailed.html", null ],
      [ "application.types.repositoryissue.RepositoryIssue", "classapplication_1_1types_1_1repositoryissue_1_1RepositoryIssue.html", null ],
      [ "application.types.schema.Schema", "classapplication_1_1types_1_1schema_1_1Schema.html", null ],
      [ "application.types.schemaparam.SchemaParam", "classapplication_1_1types_1_1schemaparam_1_1SchemaParam.html", null ],
      [ "application.types.schemaquery.SchemaQuery", "classapplication_1_1types_1_1schemaquery_1_1SchemaQuery.html", null ],
      [ "application.types.schemareturntype.SchemaReturnType", "classapplication_1_1types_1_1schemareturntype_1_1SchemaReturnType.html", null ],
      [ "application.types.schematype.SchemaType", "classapplication_1_1types_1_1schematype_1_1SchemaType.html", null ],
      [ "application.types.sorting.Sorting", "classapplication_1_1types_1_1sorting_1_1Sorting.html", null ],
      [ "application.types.sorting_.Sorting_", "classapplication_1_1types_1_1sorting___1_1Sorting__.html", null ],
      [ "application.types.subscription.Subscription", "classapplication_1_1types_1_1subscription_1_1Subscription.html", null ],
      [ "application.types.subscriptionkeys.SubscriptionKeys", "classapplication_1_1types_1_1subscriptionkeys_1_1SubscriptionKeys.html", null ],
      [ "application.types.subscriptionlist.SubscriptionList", "classapplication_1_1types_1_1subscriptionlist_1_1SubscriptionList.html", null ],
      [ "application.types.subscriptiontoken.SubscriptionToken", "classapplication_1_1types_1_1subscriptiontoken_1_1SubscriptionToken.html", null ],
      [ "application.types.subscriptiontokenkeys.SubscriptionTokenKeys", "classapplication_1_1types_1_1subscriptiontokenkeys_1_1SubscriptionTokenKeys.html", null ],
      [ "application.types.subsonicalbum.SubsonicAlbum", "classapplication_1_1types_1_1subsonicalbum_1_1SubsonicAlbum.html", null ],
      [ "application.types.subsonicerror.SubsonicError", "classapplication_1_1types_1_1subsonicerror_1_1SubsonicError.html", null ],
      [ "application.types.subsonicsearch.SubsonicSearch", "classapplication_1_1types_1_1subsonicsearch_1_1SubsonicSearch.html", null ],
      [ "application.types.subsonictrack.SubsonicTrack", "classapplication_1_1types_1_1subsonictrack_1_1SubsonicTrack.html", null ],
      [ "application.types.systeminfo.SystemInfo", "classapplication_1_1types_1_1systeminfo_1_1SystemInfo.html", null ],
      [ "application.types.theme.Theme", "classapplication_1_1types_1_1theme_1_1Theme.html", null ],
      [ "application.types.themecolor.ThemeColor", "classapplication_1_1types_1_1themecolor_1_1ThemeColor.html", null ],
      [ "application.types.themecolor_.ThemeColor_", "classapplication_1_1types_1_1themecolor___1_1ThemeColor__.html", null ],
      [ "application.types.themesize.ThemeSize", "classapplication_1_1types_1_1themesize_1_1ThemeSize.html", null ],
      [ "application.types.themesize_.ThemeSize_", "classapplication_1_1types_1_1themesize___1_1ThemeSize__.html", null ],
      [ "application.types.userbookcount.UserBookCount", "classapplication_1_1types_1_1userbookcount_1_1UserBookCount.html", null ],
      [ "application.types.userdata.UserData", "classapplication_1_1types_1_1userdata_1_1UserData.html", null ],
      [ "application.types.userdoesnotexisterror.UserDoesNotExistError", "classapplication_1_1types_1_1userdoesnotexisterror_1_1UserDoesNotExistError.html", null ],
      [ "application.types.userexistserror.UserExistsError", "classapplication_1_1types_1_1userexistserror_1_1UserExistsError.html", null ],
      [ "application.types.usermindata.UserMinData", "classapplication_1_1types_1_1usermindata_1_1UserMinData.html", null ],
      [ "application.types.usertheme.UserTheme", "classapplication_1_1types_1_1usertheme_1_1UserTheme.html", null ],
      [ "application.types.usertheme_.UserTheme_", "classapplication_1_1types_1_1usertheme___1_1UserTheme__.html", null ],
      [ "application.types.weatheralert.WeatherAlert", "classapplication_1_1types_1_1weatheralert_1_1WeatherAlert.html", null ],
      [ "application.types.weatherexecution.WeatherExecution", "classapplication_1_1types_1_1weatherexecution_1_1WeatherExecution.html", null ],
      [ "application.types.weathertemp.WeatherTemp", "classapplication_1_1types_1_1weathertemp_1_1WeatherTemp.html", null ],
      [ "application.types.weathertemp_.WeatherTemp_", "classapplication_1_1types_1_1weathertemp___1_1WeatherTemp__.html", null ],
      [ "application.types.weatheruser.WeatherUser", "classapplication_1_1types_1_1weatheruser_1_1WeatherUser.html", null ],
      [ "application.types.weatheruserinput.WeatherUserInput", "classapplication_1_1types_1_1weatheruserinput_1_1WeatherUserInput.html", null ],
      [ "application.types.webpushexception.WebPushException", "classapplication_1_1types_1_1webpushexception_1_1WebPushException.html", null ],
      [ "application.types.zipprogress.ZipProgress", "classapplication_1_1types_1_1zipprogress_1_1ZipProgress.html", null ]
    ] ]
];