name: Deploy documentation

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get install -y python3-poetry python3-sphinx
    
    - name: Poetry Install
      run: poetry install --no-root --with dev

    - name: Build Documentation
      run: poetry run ./docs.sh

    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
