type Document {
	id: String!
	title: String!
	body: String!
	body_html: String!
	created: DateTime!
	creator: UserMinData!
	updated: DateTime
	updater: UserMinData
	blob_id: String
	tags: [String!]!
}

type DocumentDoesNotExistError {
	message: String!
}

type BlobDocumentsNotSupported {
	message: String!
}

"""
A type for getting the number of documents that match a query.
This type is used so that if the query fails, we can return an error message instead of zero.
"""
type DocumentCount {
	"""The number of documents that match the query"""
	count: Long!
}

type DocumentList {
	documents: [Document!]!
}

"""
An input type for filtering documents.
All fields are optional, and if a field is null, it will not be used in the query.
"""
input DocumentSearchFilter {
	"""The title of the document."""
	title: String
	"""The tag query to filter documents by."""
	tag_expr: String
	"""Whether documents are shared with the current user."""
	shared: Boolean
}

union DocumentQueryResponse = Document | DocumentDoesNotExistError | InsufficientPerms
union DocumentUpdateResponse = Document | DocumentDoesNotExistError | InsufficientPerms
union DocumentCountResponse = DocumentCount | InsufficientPerms | BadTagQuery
union CreateBlobDocumentResponse = Document | InsufficientPerms | BlobDocumentsNotSupported
union LinkBlobDocumentResponse = Document | InsufficientPerms | BlobDocumentsNotSupported | BlobDoesNotExistError
union DocumentListResponse = DocumentList | BadTagQuery

#Resolvers below this line:

extend type Query {
	getDocument(id: String!): DocumentQueryResponse!
	getDocuments(filter: DocumentSearchFilter!, start: Int!, count: Int!): DocumentListResponse!
	countDocuments(filter: DocumentSearchFilter!): DocumentCountResponse!
	countDocumentTagUses(tag: String!): Int!
}

extend type Mutation {
	createDocument(title: String!, body: String!): DocumentUpdateResponse!
	createBlobDocument(title: String!): CreateBlobDocumentResponse!
	linkBlobDocument(title: String!, blob_id: String!): LinkBlobDocumentResponse!
	updateDocument(id: String!, title: String, body: String): DocumentUpdateResponse!
	deleteDocument(id: String!): DocumentUpdateResponse!
	setDocumentTags(id: String!, tags: [String!]!): DocumentUpdateResponse!
}
